version: '3'

services:
  redis:
    image: redis
    restart: always
    environment:
      REDIS_PORT: 6379
      REDIS_DATABASES: 16
    ports:
      - "6379:6379"
    command: /usr/local/bin/redis-server --save 60 1 --loglevel warning
    volumes:
      - ./data/redis:/data

  calculator:
    restart: always
    depends_on:
      - redis
    build: ./
    volumes:
      - ./:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  
  worker:
    restart: always
    build: .
    depends_on:
      - redis
      - calculator
    volumes:
      - ./:/app
      - ./media:/app/media
    #      - ./django_page_calculator/:/usr/src/app/
    #      - ./data/django_page_calculator/media:/usr/src/app/media
    command: celery -A django_page_calculator worker -l info --pool=solo

