# Generated by Django 4.2.13 on 2024-06-13 07:02

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import page_calculator_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=650, verbose_name='Номер договора')),
                ('show', models.BooleanField(default=True, verbose_name='Отображать договор')),
            ],
            options={
                'verbose_name': 'номер договора',
                'verbose_name_plural': 'номера договоров',
                'db_table': 'ToDo_tasks_contractmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CpeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ГИП',
                'verbose_name_plural': 'ГИПЫ',
                'db_table': 'ToDo_tasks_cpemodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(default=None, max_length=250, verbose_name='Наименование объекта')),
                ('show', models.BooleanField(default=True, verbose_name='Отображать объект')),
            ],
            options={
                'verbose_name': 'наименование объекта',
                'verbose_name_plural': 'наименования объектов',
                'db_table': 'ToDo_tasks_objectmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Номер заказа')),
            ],
            options={
                'verbose_name': 'номер заказа',
                'verbose_name_plural': 'номера заказов',
                'db_table': 'ToDo_tasks_ordersmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrintPagePermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_calculator_app.employeemodel', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'сотрудник имеющий доступ к странице печати',
                'verbose_name_plural': 'сотрудники имеющие доступ к странице печати',
            },
        ),
        migrations.CreateModel(
            name='PrintFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=150, verbose_name='Название файла')),
                ('inventory_number', models.CharField(max_length=150, verbose_name='Инвентарный номер')),
                ('status', models.IntegerField(choices=[(0, 'Аннулирован'), (1, 'Актуален'), (2, 'Готов')], default=1, verbose_name='Статус номера')),
                ('file_to_print', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=page_calculator_app.models.upload_print_file, verbose_name='Файл на печать')),
                ('add_file_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('printed_date', models.DateTimeField(null=True, verbose_name='Дата распечатки')),
                ('task_type_work', models.IntegerField(choices=[(0, 'Не указан'), (1, 'РД'), (2, 'ПД'), (3, 'ОБИН'), (4, 'НИОКР')], default=0, verbose_name='Вид документации:')),
                ('emp_upload_file', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='page_calculator_app.employeemodel', verbose_name='Пользователь загрузивший файл')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_calculator_app.ordersmodel', verbose_name='Номер заказа')),
            ],
            options={
                'verbose_name': 'файл на печать',
                'verbose_name_plural': 'файлы на печать',
            },
        ),
        migrations.CreateModel(
            name='ListsFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a0', models.IntegerField(blank=True, default=0, verbose_name='A0')),
                ('a0x2', models.IntegerField(blank=True, default=0, verbose_name='A0x2')),
                ('a0x3', models.IntegerField(blank=True, default=0, verbose_name='A0x3')),
                ('a1', models.IntegerField(blank=True, default=0, verbose_name='A1')),
                ('a1x3', models.IntegerField(blank=True, default=0, verbose_name='A1x3')),
                ('a1x4', models.IntegerField(blank=True, default=0, verbose_name='A1x4')),
                ('a2', models.IntegerField(blank=True, default=0, verbose_name='A2')),
                ('a2x3', models.IntegerField(blank=True, default=0, verbose_name='A2x3')),
                ('a2x4', models.IntegerField(blank=True, default=0, verbose_name='A2x4')),
                ('a2x5', models.IntegerField(blank=True, default=0, verbose_name='A2x5')),
                ('a3', models.IntegerField(blank=True, default=0, verbose_name='A3')),
                ('a3x3', models.IntegerField(blank=True, default=0, verbose_name='A3x3')),
                ('a3x4', models.IntegerField(blank=True, default=0, verbose_name='A3x4')),
                ('a3x5', models.IntegerField(blank=True, default=0, verbose_name='A3x5')),
                ('a3x6', models.IntegerField(blank=True, default=0, verbose_name='A3x6')),
                ('a3x7', models.IntegerField(blank=True, default=0, verbose_name='A3x7')),
                ('a4', models.IntegerField(blank=True, default=0, verbose_name='A4')),
                ('a4x3', models.IntegerField(blank=True, default=0, verbose_name='A4x3')),
                ('a4x4', models.IntegerField(blank=True, default=0, verbose_name='A4x4')),
                ('a4x5', models.IntegerField(blank=True, default=0, verbose_name='A4x5')),
                ('a4x6', models.IntegerField(blank=True, default=0, verbose_name='A4x6')),
                ('a4x7', models.IntegerField(blank=True, default=0, verbose_name='A4x7')),
                ('a4x8', models.IntegerField(blank=True, default=0, verbose_name='A4x8')),
                ('a4x9', models.IntegerField(blank=True, default=0, verbose_name='A4x9')),
                ('other_pages', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Другое')),
                ('print_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_calculator_app.printfilesmodel')),
            ],
            options={
                'verbose_name': 'лист файла',
                'verbose_name_plural': 'листы файлов',
            },
        ),
    ]
