# Generated by Django 4.2.13 on 2024-06-13 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0002_contractmodel_cpemodel_objectmodel_ordersmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printfilesmodel',
            old_name='printed_date',
            new_name='date_change_status',
        ),
        migrations.RenameField(
            model_name='printfilesmodel',
            old_name='inventory_number',
            new_name='inventory_number_file',
        ),
        migrations.AddField(
            model_name='printfilesmodel',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_calculator_app.contractmodel', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='printfilesmodel',
            name='copy_count',
            field=models.IntegerField(blank=True, default=1, verbose_name='Количество копий'),
        ),
        migrations.AddField(
            model_name='printfilesmodel',
            name='inventory_number_request',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер заявки'),
        ),
        migrations.AddField(
            model_name='printfilesmodel',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_calculator_app.objectmodel', verbose_name='Объект'),
        ),
    ]
