# Generated by Django 4.2.13 on 2024-06-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0003_rename_printed_date_printfilesmodel_date_change_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountTasksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество заявок')),
                ('date_of_print', models.CharField(max_length=150, verbose_name='Дата обработки заявок')),
                ('auto_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата для сортировок')),
            ],
            options={
                'verbose_name': 'счетчик печати',
                'verbose_name_plural': 'счетчики печати',
            },
        ),
    ]
