# Generated by Django 4.2.13 on 2024-06-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0004_counttasksmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfilesmodel',
            name='type_task',
            field=models.IntegerField(choices=[(0, 'Не указан'), (1, 'Скан'), (2, 'Печать'), (3, 'Тираж')], default=0, verbose_name='Тип задачи'),
        ),
    ]
