# Generated by Django 4.2.13 on 2024-06-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0005_printfilesmodel_type_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfilesmodel',
            name='count_pages',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество листов'),
        ),
        migrations.AlterField(
            model_name='printfilesmodel',
            name='date_change_status',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата распечатки'),
        ),
    ]
