# Generated by Django 4.2.13 on 2024-06-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0006_printfilesmodel_count_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfilesmodel',
            name='a4_count_formats',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество форматов а4'),
        ),
    ]
