# Generated by Django 4.2.13 on 2024-06-14 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0007_printfilesmodel_a4_count_formats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listsfilemodel',
            name='print_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page_calculator_app.printfilesmodel'),
        ),
    ]
