# Generated by Django 4.2.13 on 2024-06-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0008_alter_listsfilemodel_print_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfilesmodel',
            name='user_clearance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Допуск подсчета у пользователя'),
        ),
    ]
