# Generated by Django 4.2.13 on 2024-06-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0009_printfilesmodel_user_clearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printfilesmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Аннулирован'), (1, 'Актуален'), (2, 'В работе'), (3, 'Готов')], default=1, verbose_name='Статус номера'),
        ),
    ]
