# Generated by Django 4.2.13 on 2024-06-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0010_alter_printfilesmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfilesmodel',
            name='print_folding',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Фальцовка'),
        ),
    ]
