# Generated by Django 4.2.13 on 2024-06-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0011_printfilesmodel_print_folding'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfilesmodel',
            name='color',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Цветное'),
        ),
    ]
