# Generated by Django 4.2.13 on 2024-06-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0012_printfilesmodel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='listsfilemodel',
            name='a0_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A0'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a0x2_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A0x2'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a0x3_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A0x3'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a1_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A1'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a1x3_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A1x3'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a1x4_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A1x4'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a2_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A2'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a2x3_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A2x3'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a2x4_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A2x4'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a2x5_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A2x5'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a3_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A3'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a3x3_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A3x3'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a3x4_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A3x4'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a3x5_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A3x5'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a3x6_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A3x6'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a3x7_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A3x7'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a4_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a4x3_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4x3'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a4x4_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4x4'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a4x5_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4x5'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a4x6_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4x6'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a4x7_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4x7'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a4x8_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4x8'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='a4x9_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4x9'),
        ),
        migrations.AddField(
            model_name='listsfilemodel',
            name='other_pages_color',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Другое'),
        ),
        migrations.CreateModel(
            name='ChangeStatusHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Аннулирован'), (1, 'Актуален'), (2, 'В работе'), (3, 'Готов')], default=1, verbose_name='Статус номера')),
                ('date_change_status', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата изменения')),
                ('emp', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='page_calculator_app.employeemodel', verbose_name='Сотрудник')),
                ('print_task', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='page_calculator_app.printfilesmodel', verbose_name='Задание на печать')),
            ],
            options={
                'verbose_name': 'история изменения',
                'verbose_name_plural': 'история изменений',
            },
        ),
    ]
