# Generated by Django 4.2.13 on 2024-07-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0013_listsfilemodel_a0_color_listsfilemodel_a0x2_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkDocModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_doc', models.CharField(max_length=5, verbose_name='Краткое название марки')),
                ('mark_doc_full_name', models.CharField(max_length=150, verbose_name='Полное название')),
            ],
            options={
                'verbose_name': 'марка документации',
                'verbose_name_plural': 'марки документации',
                'db_table': 'ToDo_tasks_markdocmodel',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a0_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A0_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a0x2_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A0x2_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a0x3_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A0x3_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a1_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A1_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a1x3_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A1x3_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a1x4_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A1x4_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a2_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A2_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a2x3_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A2x3_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a2x4_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A2x4_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a2x5_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A2x5_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a3_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A3_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a3x3_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A3x3_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a3x4_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A3x4_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a3x5_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A3x5_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a3x6_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A3x6_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a3x7_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A3x7_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a4_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a4x3_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4x3_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a4x4_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4x4_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a4x5_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4x5_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a4x6_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4x6_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a4x7_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4x7_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a4x8_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4x8_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='a4x9_color',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4x9_color'),
        ),
        migrations.AlterField(
            model_name='listsfilemodel',
            name='other_pages_color',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Другое_color'),
        ),
    ]
