# Generated by Django 4.2.13 on 2024-07-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0014_markdocmodel_alter_listsfilemodel_a0_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersmodel',
            options={'managed': False, 'verbose_name': 'номер заказчика', 'verbose_name_plural': 'номера заказчиков'},
        ),
    ]
