# Generated by Django 4.2.13 on 2024-07-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0015_alter_ordersmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfilesmodel',
            name='mark_print_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_calculator_app.markdocmodel', verbose_name='Марка документации'),
        ),
    ]
