# Generated by Django 4.2.13 on 2024-07-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0017_alter_printfilesmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfilesmodel',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий'),
        ),
    ]
