# Generated by Django 4.2.13 on 2024-10-15 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0018_printfilesmodel_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivePrintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер разрешения')),
                ('purpose_of_printing', models.IntegerField(choices=[(0, 'Для аннулирования (печать титульных листов'), (1, 'Для внесения изменений')], default=0, verbose_name='Тип вносимых изменений:')),
            ],
            options={
                'verbose_name': 'информация печати из архива',
                'verbose_name_plural': 'информация печати из архива',
            },
        ),
        migrations.AddField(
            model_name='printfilesmodel',
            name='print_from_archive',
            field=models.BooleanField(default=False, verbose_name='Печать из архива'),
        ),
        migrations.AddField(
            model_name='printfilesmodel',
            name='print_from_archive_details',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_calculator_app.archiveprintmodel', verbose_name='Детали печати из архива'),
        ),
    ]
