# Generated by Django 4.2.13 on 2024-10-16 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_calculator_app', '0020_alter_archiveprintmodel_purpose_of_printing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printfilesmodel',
            name='print_from_archive_details',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='page_calculator_app.archiveprintmodel', verbose_name='Детали печати из архива'),
        ),
    ]
